name: Release
run-name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - '**'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: bigwigsmods/packager@v2